version: 2
updates:
- package-ecosystem: gradle
  directory: /
  schedule:
    # Defaults to first day of the month.
    interval: monthly
  open-pull-requests-limit: 20
  reviewers:
  - al-jeyapal
  - lewis-russell
  - adam-kimpton
  labels:
  - dependencies
  ignore:
    # The version of the `error_prone_core` dependency is dependent on the version of the
    # `errorprone` plugin, and they must be kept in sync, so we prevent Dependabot from updating
    # them.
    - dependency-name: "net.ltgt.errorprone"
    - dependency-name: "com.google.errorprone:error_prone_core"
    # We prevent Dependabot from updating Spock because we need to align the version with whatever
    # Groovy version the current Gradle version supports.
    - dependency-name: "org.spockframework:spock-bom"
